<a href="https://colab.research.google.com/github/emanuelmejia/course_time_series_python/blob/main/L05-Regresion/notebooks/L05_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

#Sección Holt Winters
from statsmodels.tsa.holtwinters import ExponentialSmoothing

#Sección Regresión
import statsmodels.formula.api as smf
import statsmodels.graphics.tsaplots as smt
import seaborn as sns

In [6]:
# Subir archivo aus_production.csv
from google.colab import files
files.upload()

Saving aus_production.csv to aus_production (1).csv

{'aus_production (1).csv': b'"ds","Beer","Tobacco","Bricks","Cement","Electricity","Gas"\n1956-01-01,284,5225,189,465,3923,5\n1956-04-01,213,5178,204,532,4436,6\n1956-07-01,227,5297,208,561,4806,7\n1956-10-01,308,5681,197,570,4418,6\n1957-01-01,262,5577,187,529,4339,5\n1957-04-01,228,5651,214,604,4811,7\n1957-07-01,236,5317,227,603,5259,7\n1957-10-01,320,6152,222,582,4735,6\n1958-01-01,272,5758,199,554,4608,5\n1958-04-01,233,5641,229,620,5196,7\n1958-07-01,237,5802,249,646,5609,8\n1958-10-01,313,6265,234,637,4977,6\n1959-01-01,261,5478,208,573,4883,5\n1959-04-01,227,5892,251,673,5744,7\n1959-07-01,250,5952,267,690,6035,8\n1959-10-01,314,6597,255,681,5514,6\n1960-01-01,286,5980,242,621,5387,6\n1960-04-01,227,6154,268,698,6211,8\n1960-07-01,260,5478,290,753,6659,8\n1960-10-01,311,6716,277,728,5983,7\n1961-01-01,295,6022,241,688,5709,6\n1961-04-01,233,6070,253,737,6458,7\n1961-07-01,257,6303,265,742,6875,8\n1961-10-01,339,6693,236,692,6162,6\n1962-01-01,279,6072,229,637,6098,6\n1962-04-01,250,6112,265,757,7075,8\n1962-07-01,270,6146,275,783,7595,8\n1962-10-01,346,6787,258,757,6891,7\n1963-01-01,294,6051,231,674,6707,6\n1963-04-01,255,6259,263,774,7874,8\n1963-07-01,278,6348,308,835,8555,9\n1963-10-01,363,6883,313,838,7503,7\n1964-01-01,313,5890,293,797,7469,6\n1964-04-01,273,6365,328,904,8829,8\n1964-07-01,300,7373,349,949,9513,9\n1964-10-01,370,6768,340,975,8415,7\n1965-01-01,331,6201,309,902,8170,6\n1965-04-01,288,6332,349,974,9503,8\n1965-07-01,306,7213,366,969,10306,9\n1965-10-01,386,6600,340,967,9077,7\n1966-01-01,335,5522,302,849,8650,6\n1966-04-01,288,6184,350,961,10180,8\n1966-07-01,308,7202,362,966,11234,10\n1966-10-01,402,6599,337,922,9836,7\n1967-01-01,353,5801,306,836,9490,6\n1967-04-01,316,6771,358,998,10991,9\n1967-07-01,325,6837,359,1025,12170,10\n1967-10-01,405,6685,357,971,10470,7\n1968-01-01,393,6255,341,892,10087,6\n1968-04-01,319,6977,380,973,11858,9\n1968-07-01,327,7417,404,1047,13198,11\n1968-10-01,442,7075,409,1017,11413,8\n1969-01-01,383,6641,383,948,11136,7\n1969-04-01,332,7154,417,1032,13040,10\n1969-07-01,361,7929,454,1190,14248,13\n1969-10-01,446,7362,428,1136,12759,11\n1970-01-01,387,6807,386,1049,12328,12\n1970-04-01,357,7612,428,1134,14493,18\n1970-07-01,374,7862,434,1229,15664,23\n1970-10-01,466,7126,417,1188,13781,20\n1971-01-01,410,7255,385,1058,13299,19\n1971-04-01,370,8076,433,1209,15230,23\n1971-07-01,379,8405,453,1199,16667,28\n1971-10-01,487,7974,436,1253,14484,24\n1972-01-01,419,6500,399,1070,13838,24\n1972-04-01,378,7119,461,1282,15919,34\n1972-07-01,393,7367,476,1303,17149,40\n1972-10-01,506,7549,477,1281,15564,35\n1973-01-01,458,7168,452,1148,15024,34\n1973-04-01,387,7635,461,1305,17064,41\n1973-07-01,427,8446,534,1342,18512,48\n1973-10-01,565,7593,516,1452,16467,39\n1974-01-01,465,6823,478,1184,16249,38\n1974-04-01,445,7856,526,1352,18515,48\n1974-07-01,450,8574,518,1316,20377,52\n1974-10-01,556,8163,417,1353,17681,43\n1975-01-01,500,6971,340,1121,16692,39\n1975-04-01,452,8021,437,1297,19184,49\n1975-07-01,435,8133,459,1318,20078,55\n1975-10-01,554,8349,449,1281,18260,47\n1976-01-01,510,6687,424,1109,18023,44\n1976-04-01,433,7991,501,1299,20234,58\n1976-07-01,453,6900,540,1341,22272,65\n1976-10-01,548,7119,533,1290,19684,54\n1977-01-01,486,7156,457,1101,19031,49\n1977-04-01,453,8671,513,1284,21545,64\n1977-07-01,457,8459,522,1321,23270,74\n1977-10-01,566,7367,478,1317,20107,58\n1978-01-01,515,7219,421,1122,20084,56\n1978-04-01,464,7344,487,1261,22634,71\n1978-07-01,431,7314,470,1312,24494,78\n1978-10-01,588,7379,482,1298,21396,65\n1979-01-01,503,7084,458,1205,21323,59\n1979-04-01,443,7882,526,1302,23644,74\n1979-07-01,448,7816,573,1377,25994,88\n1979-10-01,555,6786,563,1359,22802,71\n1980-01-01,513,6794,513,1232,22604,68\n1980-04-01,427,8168,551,1386,24510,91\n1980-07-01,473,8097,589,1440,26690,103\n1980-10-01,526,7820,564,1439,24132,83\n1981-01-01,548,6437,519,1282,23639,88\n1981-04-01,440,7995,581,1573,26320,110\n1981-07-01,469,8238,581,1533,28345,120\n1981-10-01,575,8026,578,1641,24890,101\n1982-01-01,493,6697,501,1337,24675,93\n1982-04-01,433,7749,560,1575,27122,116\n1982-07-01,480,8043,512,1475,28590,127\n1982-10-01,576,7469,412,1357,25371,98\n1983-01-01,475,6559,303,1086,24687,92\n1983-04-01,405,7852,409,1158,27285,118\n1983-07-01,435,7449,420,1279,29290,124\n1983-10-01,535,6975,413,1313,26684,104\n1984-01-01,453,6631,400,1166,26641,97\n1984-04-01,430,6928,469,1373,29042,116\n1984-07-01,417,6542,482,1456,31856,130\n1984-10-01,552,6819,484,1495,28343,111\n1985-01-01,464,6033,447,1251,28982,103\n1985-04-01,417,7678,507,1456,30838,120\n1985-07-01,423,7341,533,1631,33165,132\n1985-10-01,554,6829,505,1555,29648,107\n1986-01-01,459,5733,442,1375,29506,98\n1986-04-01,428,7465,503,1546,32002,127\n1986-07-01,429,7780,506,1568,34375,137\n1986-10-01,534,7234,443,1561,31046,112\n1987-01-01,481,5765,414,1332,31015,106\n1987-04-01,416,7476,485,1458,33685,130\n1987-07-01,440,6742,495,1501,35850,158\n1987-10-01,538,7217,458,1615,33211,123\n1988-01-01,474,6034,428,1418,33142,116\n1988-04-01,440,7389,519,1625,34664,137\n1988-07-01,447,7077,555,1770,37154,157\n1988-10-01,598,6837,538,1791,35303,125\n1989-01-01,467,6051,510,1621,36905,117\n1989-04-01,439,7193,571,1719,37333,149\n1989-07-01,446,6639,556,1972,40413,175\n1989-10-01,567,7060,509,1894,36579,139\n1990-01-01,485,6562,458,1565,37016,125\n1990-04-01,441,7063,510,1645,39103,152\n1990-07-01,429,7374,494,1658,41067,161\n1990-10-01,599,6563,460,1668,37653,123\n1991-01-01,464,6202,372,1343,37554,111\n1991-04-01,424,6694,436,1441,38752,141\n1991-07-01,436,6748,422,1444,41424,160\n1991-10-01,574,6160,423,1497,38101,125\n1992-01-01,443,5777,383,1289,38332,117\n1992-04-01,410,5853,404,1501,39774,151\n1992-07-01,420,6416,446,1539,42246,175\n1992-10-01,532,5825,420,1568,38498,129\n1993-01-01,433,5724,394,1450,39460,116\n1993-04-01,421,6036,462,1668,41356,149\n1993-07-01,410,6570,475,1648,42949,163\n1993-10-01,512,5675,443,1863,40974,138\n1994-01-01,449,5311,421,1468,40162,127\n1994-04-01,381,5717,475,1755,41199,159\n1994-07-01,423,7000,497,1962,44095,184\n1994-10-01,531,6085,476,1833,41745,147\n1995-01-01,426,4714,430,1626,41768,131\n1995-04-01,408,3939,457,1703,43686,167\n1995-07-01,416,6137,417,1733,46022,181\n1995-10-01,520,4739,370,1545,42800,145\n1996-01-01,409,4275,310,1526,43661,133\n1996-04-01,398,5239,358,1593,44707,162\n1996-07-01,398,6293,379,1706,46326,184\n1996-10-01,507,5575,369,1699,43346,146\n1997-01-01,432,4802,330,1511,43938,135\n1997-04-01,398,5523,390,1785,45828,171\n1997-07-01,406,5708,416,1826,48448,183\n1997-10-01,526,4821,383,1830,46096,151\n1998-01-01,428,4919,339,1719,46198,141\n1998-04-01,397,5809,394,1861,47237,174\n1998-07-01,403,5904,412,1956,49041,191\n1998-10-01,517,4555,420,2067,46192,157\n1999-01-01,435,5198,376,1737,48089,145\n1999-04-01,383,5388,401,1944,48227,182\n1999-07-01,424,5142,430,2005,49784,198\n1999-10-01,521,5517,417,2027,47588,165\n2000-01-01,421,5169,416,1835,49320,164\n2000-04-01,402,4860,447,2070,50670,199\n2000-07-01,414,5185,421,1898,52623,213\n2000-10-01,500,4763,379,1652,49350,173\n2001-01-01,451,4217,304,1554,51658,177\n2001-04-01,380,4959,337,1717,51103,205\n2001-07-01,416,5196,385,1679,52226,218\n2001-10-01,492,4522,381,1836,50778,185\n2002-01-01,428,3843,345,1729,50639,166\n2002-04-01,408,4806,405,1992,51486,204\n2002-07-01,406,5280,417,2030,53299,228\n2002-10-01,506,4709,420,1978,51646,186\n2003-01-01,435,4362,387,1831,51415,172\n2003-04-01,380,5210,415,1892,51379,204\n2003-07-01,421,5258,440,2227,54808,232\n2003-10-01,490,4526,413,2090,52453,188\n2004-01-01,435,3974,409,1963,54561,173\n2004-04-01,390,5027,423,2180,54644,215\n2004-07-01,412,NA,428,2307,55915,227\n2004-10-01,454,NA,397,2157,52850,190\n2005-01-01,416,NA,355,1980,55035,170\n2005-04-01,403,NA,435,2481,55117,206\n2005-07-01,408,NA,NA,2340,56043,221\n2005-10-01,482,NA,NA,2265,54992,180\n2006-01-01,438,NA,NA,2027,57112,171\n2006-04-01,386,NA,NA,2278,57157,224\n2006-07-01,405,NA,NA,2427,58400,233\n2006-10-01,491,NA,NA,2451,56249,192\n2007-01-01,427,NA,NA,2140,56244,187\n2007-04-01,383,NA,NA,2362,55036,234\n2007-07-01,394,NA,NA,2536,59806,245\n2007-10-01,473,NA,NA,2562,56411,205\n2008-01-01,420,NA,NA,2183,59118,194\n2008-04-01,390,NA,NA,2558,56660,229\n2008-07-01,410,NA,NA,2612,64067,249\n2008-10-01,488,NA,NA,2373,59045,203\n2009-01-01,415,NA,NA,1963,58368,196\n2009-04-01,398,NA,NA,2160,57471,238\n2009-07-01,419,NA,NA,2325,58394,252\n2009-10-01,488,NA,NA,2273,57336,210\n2010-01-01,414,NA,NA,1904,58309,205\n2010-04-01,374,NA,NA,2401,58041,236\n'}

In [7]:
df_full = pd.read_csv("/content/aus_production.csv")
df_full['Fecha'] = pd.period_range(start='1956-01', periods=len(df_full), freq='Q')
df_full = df_full.set_index('Fecha')
df_full.index = df_full.index.to_timestamp()
df_full

                    ds  Beer  Tobacco  Bricks  Cement  Electricity  Gas
Fecha
1956-01-01  1956-01-01   284   5225.0   189.0     465         3923    5
1956-04-01  1956-04-01   213   5178.0   204.0     532         4436    6
1956-07-01  1956-07-01   227   5297.0   208.0     561         4806    7
1956-10-01  1956-10-01   308   5681.0   197.0     570         4418    6
1957-01-01  1957-01-01   262   5577.0   187.0     529         4339    5
...                ...   ...      ...     ...     ...          ...  ...
2009-04-01  2009-04-01   398      NaN     NaN    2160        57471  238
2009-07-01  2009-07-01   419      NaN     NaN    2325        58394  252
2009-10-01  2009-10-01   488      NaN     NaN    2273        57336  210
2010-01-01  2010-01-01   414      NaN     NaN    1904        58309  205
2010-04-01  2010-04-01   374      NaN     NaN    2401        58041  236

[218 rows x 7 columns]

# **Sección Modelos Básicos**

Seleccionar una columna de df_full que no sea 'Bricks' ni 'Gas', utilizando la celda debajo.

- Generar un gráfico inicial de observación de la serie
- Generar un gráfico para los siguientes Métodos de Pronóstico:
  - Promedio
  - Naive
  - Naive Estacional
  - Drift
- Generar DataFrame llamado dfForecast en donde se guarden los datos de cada uno de los pronósticos

*NOTA: Este flujo de trabajo es el mismo realizado en el cuaderno L03-2-BasicToolbox.ipynb*

- Por último generar una conclusión con base en la siguiente pregunta: ¿Si estos fuesen los únicos métodos de pronóstico disponibles, cuál parece más apropiado para los datos seleccionados y por qué?

In [8]:
# Ingresar el nombre de la columna de interés en el código debajo
# DIFERENTE DE 'Bricks' y 'Gas'
columna = 'Bricks'

df = df_full[columna].to_frame()
df = df.dropna()
df.head()

            Bricks
Fecha
1956-01-01   189.0
1956-04-01   204.0
1956-07-01   208.0
1956-10-01   197.0
1957-01-01   187.0

# **Sección Holt Winters**

Ajustar, a la columna seleccionada del ejercicio anterior, por lo menos:
- Un método de Suavizamiento Exponencial con $\alpha$ seleccionada manualmente
- Un método de Suavizamiento Holt-Winters con parámetros [$\alpha$, $\beta$, $\gamma$] seleccionados manualmente (entre 0 y 1)
- Un método de Suavizamiento Holt-Winters con parámetros [$\alpha$, $\beta$, $\gamma$] seleccionados automáticamente.
- Elaborar un pronóstico utilizando cualquiera de los métodos anteriores para 20 trimestres y graficarlo.

*NOTA: Este flujo de trabajo es el mismo realizado en los cuadernos L04_2-Suavizamiento.ipynb y L04_3-HoltWinters.ipynb*

- Por último generar una conclusión con base en la siguiente pregunta: ¿Si estos fuesen los únicos métodos de pronóstico disponibles, cuál parece más apropiado para los datos seleccionados y por qué?

# **Sección Regresión**

Ajustar, utilizando la columna seleccionada como variable dependiente $y$ por lo menos:
- Un modelo de regresión lineal utilizando únicamente parámetros propios de las series de tiempo (tendencia, estacionalidad o alguna de sus transformaciones)
- Un modelo de regresión lineal utilizando únicamente otras columnas como predictores (por ejemplo, si seleccioné la columna 'Beer' como variable dependiente, utilizar alguna o algunas de las columnas restantes de df_full para el modelo)
- Un modelo de regresión lineal utilizando una mezcla entre predictores de series de tiempo y variables externas (es decir un modelo que mezcle componentes de los dos puntos anteriores)
- Generar una tabla comparativa de los Criterios de Bondad de Ajuste de los 3 modelos

*NOTA: El primero y último punto de este flujo de trabajo es el mismo que el realizado en el cuaderno L05-1-RegresionST, el segundo punto es similar a alguno de los modelos realizados en el cuaderno L00-Modelos_Regresión y el tercer punto es algo que no hemos hecho hasta este momento pero es intuitivo haciendo los dos puntos anteriores*

- Por último generar una conclusión con base en la siguiente pregunta: ¿Con base en los modelos desarrollados, cuál me parece más apropiado para pronosticar la variable dependiente seleccionada?

***IMPORTANTE: Para los puntos 2 y 3 es necesario utilizar el dataframe completo 'df_full' pues es el que contiene todas las columnas***

In [9]:
# Ejemplo creando la columna de tendencia
df_full = df_full.dropna()
df_full['tend'] = np.arange(len(df_full))
df_full

/tmp/ipykernel_939/1244837233.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full['tend'] = np.arange(len(df_full))

                    ds  Beer  Tobacco  Bricks  Cement  Electricity  Gas  tend
Fecha
1956-01-01  1956-01-01   284   5225.0   189.0     465         3923    5     0
1956-04-01  1956-04-01   213   5178.0   204.0     532         4436    6     1
1956-07-01  1956-07-01   227   5297.0   208.0     561         4806    7     2
1956-10-01  1956-10-01   308   5681.0   197.0     570         4418    6     3
1957-01-01  1957-01-01   262   5577.0   187.0     529         4339    5     4
...                ...   ...      ...     ...     ...          ...  ...   ...
2003-04-01  2003-04-01   380   5210.0   415.0    1892        51379  204   189
2003-07-01  2003-07-01   421   5258.0   440.0    2227        54808  232   190
2003-10-01  2003-10-01   490   4526.0   413.0    2090        52453  188   191
2004-01-01  2004-01-01   435   3974.0   409.0    1963        54561  173   192
2004-04-01  2004-04-01   390   5027.0   423.0    2180        54644  215   193

[194 rows x 8 columns]